-- MySQL Script generated by MySQL Workbench
-- 07/18/15 08:58:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SolaFide_v6
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SolaFide_v6
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SolaFide_v6` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `SolaFide_v6` ;

-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Pessoa_Juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Pessoa_Juridica` (
  `id_Pessoa_Juridica` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(50) NOT NULL,
  `nome_fantasia` VARCHAR(50) NOT NULL,
  `representante` VARCHAR(75) NOT NULL,
  `cnpj` VARCHAR(18) NULL,
  `area_atuacao` VARCHAR(20) NULL,
  `site` VARCHAR(120) NULL,
  `comentarios` TEXT(300) NULL,
  `status` VARCHAR(22) NULL,
  PRIMARY KEY (`id_Pessoa_Juridica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Pessoa_Fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Pessoa_Fisica` (
  `id_Pessoa_Fisica` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(75) NOT NULL,
  `cpf` VARCHAR(11) NULL,
  `rg` VARCHAR(9) NULL,
  `dt_expedicao` DATE NULL,
  `orgao_exped` VARCHAR(6) NULL,
  `cnh` VARCHAR(11) NULL,
  `tempo_habilitacao` VARCHAR(2) NULL,
  `especif_temp_hap` VARCHAR(5) NULL,
  `dt_nascimento` DATE NULL,
  `profissao` VARCHAR(40) NULL,
  `comentarios` VARCHAR(300) NULL,
  `status` VARCHAR(22) NULL,
  PRIMARY KEY (`id_Pessoa_Fisica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Questionario_Seguro_Auto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Questionario_Seguro_Auto` (
  `id_questionario` INT NOT NULL AUTO_INCREMENT,
  `cep_pernoite` VARCHAR(9) NULL,
  `qtde_sinis_ult_perio` VARCHAR(3) NULL,
  `bonus` DOUBLE NULL,
  `uso_veiculo` VARCHAR(15) NULL,
  `resid_princ_cond_pes_18_24` VARCHAR(50) NULL,
  `distan_resi_trab_km` VARCHAR(5) NULL,
  `principal_condutor_estuda` VARCHAR(3) NULL,
  `veiculo_usado_cli_forn` VARCHAR(3) NULL,
  `roub_veic_ult_dois_anos` VARCHAR(3) NULL,
  `Possui_FIlhos_ate_17` VARCHAR(3) NULL,
  `garagem_fechada` VARCHAR(3) NULL,
  `profissao` VARCHAR(20) NULL,
  `segurado_proprie_veicu` VARCHAR(3) NULL,
  `quantos_filhos` INT(3) NULL,
  `cep_trabalho` VARCHAR(9) NULL,
  `tb_Pessoa_Fisica_id_Pessoa_Fisica` INT NULL,
  `tb_Pessoa_Juridica_id_Pessoa_Juridica` INT NULL,
  `Seguradora_quest` VARCHAR(30) NULL,
  `Km_Media_Mensal` VARCHAR(6) NULL,
  PRIMARY KEY (`id_questionario`),
  INDEX `fk_tb_Questionario_Seguro_Auto_tb_Pessoa_Fisica1_idx` (`tb_Pessoa_Fisica_id_Pessoa_Fisica` ASC),
  INDEX `fk_tb_Questionario_Seguro_Auto_tb_Pessoa_Juridica1_idx` (`tb_Pessoa_Juridica_id_Pessoa_Juridica` ASC),
  CONSTRAINT `fk_tb_Questionario_Seguro_Auto_tb_Pessoa_Fisica1`
    FOREIGN KEY (`tb_Pessoa_Fisica_id_Pessoa_Fisica`)
    REFERENCES `SolaFide_v6`.`tb_Pessoa_Fisica` (`id_Pessoa_Fisica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_Questionario_Seguro_Auto_tb_Pessoa_Juridica1`
    FOREIGN KEY (`tb_Pessoa_Juridica_id_Pessoa_Juridica`)
    REFERENCES `SolaFide_v6`.`tb_Pessoa_Juridica` (`id_Pessoa_Juridica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Dados_Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Dados_Veiculo` (
  `id_Dados_Veiculo` INT NOT NULL AUTO_INCREMENT,
  `fabricante` VARCHAR(30) NOT NULL,
  `modelo` VARCHAR(30) NOT NULL,
  `placa` VARCHAR(9) NULL,
  `renavam` VARCHAR(11) NULL,
  `cor_veiculo` VARCHAR(15) NOT NULL,
  `qtde_portas` VARCHAR(2) NULL,
  `tipo_combustivel` VARCHAR(10) NOT NULL,
  `chassi` VARCHAR(17) NULL,
  `financiamento` VARCHAR(14) NULL,
  `kit_gas` VARCHAR(3) NULL,
  `tb_Questionario_Seguro_Auto_id_questionario` INT NULL,
  `tb_Pessoa_Fisica_id_Pessoa_Fisica` INT NULL,
  `tb_Pessoa_Juridica_id_Pessoa_Juridica` INT NULL,
  `Disposit_Ant_Furto` VARCHAR(22) NULL,
  `Ano_frabric` VARCHAR(4) NULL,
  PRIMARY KEY (`id_Dados_Veiculo`),
  INDEX `fk_tb_Dados_Veiculo_tb_Questionario_Seguro_Auto1_idx` (`tb_Questionario_Seguro_Auto_id_questionario` ASC),
  INDEX `fk_tb_Dados_Veiculo_tb_Pessoa_Fisica1_idx` (`tb_Pessoa_Fisica_id_Pessoa_Fisica` ASC),
  INDEX `fk_tb_Dados_Veiculo_tb_Pessoa_Juridica1_idx` (`tb_Pessoa_Juridica_id_Pessoa_Juridica` ASC),
  CONSTRAINT `fk_tb_Dados_Veiculo_tb_Questionario_Seguro_Auto1`
    FOREIGN KEY (`tb_Questionario_Seguro_Auto_id_questionario`)
    REFERENCES `SolaFide_v6`.`tb_Questionario_Seguro_Auto` (`id_questionario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_Dados_Veiculo_tb_Pessoa_Fisica1`
    FOREIGN KEY (`tb_Pessoa_Fisica_id_Pessoa_Fisica`)
    REFERENCES `SolaFide_v6`.`tb_Pessoa_Fisica` (`id_Pessoa_Fisica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_Dados_Veiculo_tb_Pessoa_Juridica1`
    FOREIGN KEY (`tb_Pessoa_Juridica_id_Pessoa_Juridica`)
    REFERENCES `SolaFide_v6`.`tb_Pessoa_Juridica` (`id_Pessoa_Juridica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_MontagemApolice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_MontagemApolice` (
  `id_MontagemApolice` INT NOT NULL AUTO_INCREMENT,
  `ci` VARCHAR(20) NULL,
  `dt_calculo` VARCHAR(10) NULL,
  `dt_inicio` VARCHAR(10) NULL,
  `dt_fim` DATE NULL,
  `premio_seguradora` DOUBLE NULL,
  `franquia` DOUBLE NULL,
  `tipo_cobertura` VARCHAR(40) NULL,
  `dano_material` DOUBLE NULL,
  `dano_corporal` DOUBLE NULL,
  `app_morte` DOUBLE NULL,
  `app_invalidez` DOUBLE NULL,
  `dano_moral` DOUBLE NULL,
  `assist_24_horas` VARCHAR(3) NULL,
  `vidros` VARCHAR(3) NULL,
  `car_reserv` VARCHAR(3) NULL,
  `comentarios` VARCHAR(300) NULL,
  `tb_Questionario_id_questionario` INT NULL,
  `tb_Principal_Condutor_id_principal_condutor` INT NULL,
  `tb_Segundo_Condutor_id_segundo_condutor` INT NULL,
  `Seguradora_Orc` VARCHAR(30) NULL,
  `perc_comissao` INT NULL,
  `tb_Dados_Veiculo_id_Dados_Veiculo` INT NULL,
  PRIMARY KEY (`id_MontagemApolice`),
  INDEX `fk_tb_Orcamento_tb_Questionario1_idx` (`tb_Questionario_id_questionario` ASC),
  INDEX `fk_tb_Orcamento_tb_Dados_Veiculo1_idx` (`tb_Dados_Veiculo_id_Dados_Veiculo` ASC),
  CONSTRAINT `fk_tb_Orcamento_tb_Questionario1`
    FOREIGN KEY (`tb_Questionario_id_questionario`)
    REFERENCES `SolaFide_v6`.`tb_Questionario_Seguro_Auto` (`id_questionario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_Orcamento_tb_Dados_Veiculo1`
    FOREIGN KEY (`tb_Dados_Veiculo_id_Dados_Veiculo`)
    REFERENCES `SolaFide_v6`.`tb_Dados_Veiculo` (`id_Dados_Veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Proponente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Proponente` (
  `id_Proponente` INT NOT NULL AUTO_INCREMENT,
  `nomeProponente` VARCHAR(75) NOT NULL,
  `dt_nascimento` VARCHAR(8) NULL,
  `tb_MontagemApolice_id_MontagemApolice` INT NULL,
  PRIMARY KEY (`id_Proponente`),
  INDEX `fk_tb_Proponente_tb_MontagemApolice1_idx` (`tb_MontagemApolice_id_MontagemApolice` ASC),
  CONSTRAINT `fk_tb_Proponente_tb_MontagemApolice1`
    FOREIGN KEY (`tb_MontagemApolice_id_MontagemApolice`)
    REFERENCES `SolaFide_v6`.`tb_MontagemApolice` (`id_MontagemApolice`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Segundo_Condutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Segundo_Condutor` (
  `id_segundo_condutor` INT NOT NULL AUTO_INCREMENT,
  `nomeSegundCondut` VARCHAR(75) NULL,
  `dt_nascimento` VARCHAR(14) NULL,
  `tb_Questionario_Seguro_Auto_id_questionario` INT NULL,
  `CNH_Seg_Condult` VARCHAR(11) NULL,
  PRIMARY KEY (`id_segundo_condutor`),
  INDEX `fk_tb_Segundo_Condutor_tb_Questionario_Seguro_Auto1_idx` (`tb_Questionario_Seguro_Auto_id_questionario` ASC),
  CONSTRAINT `fk_tb_Segundo_Condutor_tb_Questionario_Seguro_Auto1`
    FOREIGN KEY (`tb_Questionario_Seguro_Auto_id_questionario`)
    REFERENCES `SolaFide_v6`.`tb_Questionario_Seguro_Auto` (`id_questionario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Sexo` (
  `id_Sexo` INT NOT NULL AUTO_INCREMENT,
  `sexo` VARCHAR(9) NULL,
  `tb_Pessoa_Fisica_id_Pessoa_Fisica` INT NULL,
  `tb_Proponente_id_Proponente` INT NULL,
  `tb_Segundo_Condutor_id_segundo_condutor` INT NULL,
  PRIMARY KEY (`id_Sexo`),
  INDEX `fk_tb_Sexo_tb_Pessoa_Fisica1_idx` (`tb_Pessoa_Fisica_id_Pessoa_Fisica` ASC),
  INDEX `fk_tb_Sexo_tb_Proponente1_idx` (`tb_Proponente_id_Proponente` ASC),
  INDEX `fk_tb_Sexo_tb_Segundo_Condutor1_idx` (`tb_Segundo_Condutor_id_segundo_condutor` ASC),
  CONSTRAINT `fk_tb_Sexo_tb_Pessoa_Fisica1`
    FOREIGN KEY (`tb_Pessoa_Fisica_id_Pessoa_Fisica`)
    REFERENCES `SolaFide_v6`.`tb_Pessoa_Fisica` (`id_Pessoa_Fisica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_Sexo_tb_Proponente1`
    FOREIGN KEY (`tb_Proponente_id_Proponente`)
    REFERENCES `SolaFide_v6`.`tb_Proponente` (`id_Proponente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_Sexo_tb_Segundo_Condutor1`
    FOREIGN KEY (`tb_Segundo_Condutor_id_segundo_condutor`)
    REFERENCES `SolaFide_v6`.`tb_Segundo_Condutor` (`id_segundo_condutor`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Estado_Civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Estado_Civil` (
  `id_Estado_Civil` INT NOT NULL AUTO_INCREMENT,
  `estado_civil` VARCHAR(10) NOT NULL,
  `tb_Pessoa_Fisica_id_Pessoa_Fisica` INT NULL,
  PRIMARY KEY (`id_Estado_Civil`),
  INDEX `fk_tb_Estado_Civil_tb_Pessoa_Fisica1_idx` (`tb_Pessoa_Fisica_id_Pessoa_Fisica` ASC),
  CONSTRAINT `fk_tb_Estado_Civil_tb_Pessoa_Fisica1`
    FOREIGN KEY (`tb_Pessoa_Fisica_id_Pessoa_Fisica`)
    REFERENCES `SolaFide_v6`.`tb_Pessoa_Fisica` (`id_Pessoa_Fisica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Pagamento` (
  `id_Pagamento` INT NOT NULL AUTO_INCREMENT,
  `parcelas` INT NULL,
  `tb_MontagemApolice_id_MontagemApolice` INT NULL,
  PRIMARY KEY (`id_Pagamento`),
  INDEX `fk_tb_Pagamento_tb_MontagemApolice1_idx` (`tb_MontagemApolice_id_MontagemApolice` ASC),
  CONSTRAINT `fk_tb_Pagamento_tb_MontagemApolice1`
    FOREIGN KEY (`tb_MontagemApolice_id_MontagemApolice`)
    REFERENCES `SolaFide_v6`.`tb_MontagemApolice` (`id_MontagemApolice`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Sinistro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Sinistro` (
  `id_sinistro` INT NOT NULL AUTO_INCREMENT,
  `nro_sinistro` INT NOT NULL,
  `apolice` VARCHAR(30) NOT NULL,
  `sinistro_ocorrido` VARCHAR(30) NOT NULL,
  `pessoas_envolvidas` VARCHAR(75) NOT NULL,
  `dt_sinistro` VARCHAR(14) NOT NULL,
  `acompanhamento` TEXT(300) NULL,
  PRIMARY KEY (`id_sinistro`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Endereco` (
  `id_Endereco` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(60) NULL,
  `numero` VARCHAR(7) NULL,
  `cep` VARCHAR(8) NULL,
  `bairro` VARCHAR(60) NULL,
  `cidade` VARCHAR(60) NULL,
  `uf` VARCHAR(2) NULL,
  `bloco` VARCHAR(2) NULL,
  `complemento` VARCHAR(45) NULL,
  `apto` VARCHAR(4) NULL,
  `tb_Pessoa_Juridica_id_Pessoa_Juridica` INT NULL,
  `tb_Pessoa_Fisica_id_Pessoa_Fisica` INT NULL,
  `tb_Sinistro_id_sinistro` INT NULL,
  PRIMARY KEY (`id_Endereco`),
  INDEX `fk_tb_Endereco_tb_Pessoa_Juridica1_idx` (`tb_Pessoa_Juridica_id_Pessoa_Juridica` ASC),
  INDEX `fk_tb_Endereco_tb_Pessoa_Fisica1_idx` (`tb_Pessoa_Fisica_id_Pessoa_Fisica` ASC),
  INDEX `fk_tb_Endereco_tb_Sinistro1_idx` (`tb_Sinistro_id_sinistro` ASC),
  CONSTRAINT `fk_tb_Endereco_tb_Pessoa_Juridica1`
    FOREIGN KEY (`tb_Pessoa_Juridica_id_Pessoa_Juridica`)
    REFERENCES `SolaFide_v6`.`tb_Pessoa_Juridica` (`id_Pessoa_Juridica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_Endereco_tb_Pessoa_Fisica1`
    FOREIGN KEY (`tb_Pessoa_Fisica_id_Pessoa_Fisica`)
    REFERENCES `SolaFide_v6`.`tb_Pessoa_Fisica` (`id_Pessoa_Fisica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_Endereco_tb_Sinistro1`
    FOREIGN KEY (`tb_Sinistro_id_sinistro`)
    REFERENCES `SolaFide_v6`.`tb_Sinistro` (`id_sinistro`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Seguradora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Seguradora` (
  `id_seguradora` INT NOT NULL AUTO_INCREMENT,
  `nome_seguradora` VARCHAR(30) NOT NULL,
  `site_corretor` VARCHAR(120) NULL,
  `site_principal` VARCHAR(120) NULL,
  `comentarios` VARCHAR(300) NULL,
  PRIMARY KEY (`id_seguradora`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Contato_Profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Contato_Profissional` (
  `id_contato` INT NOT NULL AUTO_INCREMENT,
  `tel_comercial` VARCHAR(20) NULL,
  `cel_comercial` VARCHAR(20) NULL,
  `nextel` VARCHAR(15) NULL,
  `email` VARCHAR(60) NULL,
  `tb_Seguradora_id_seguradora` INT NULL,
  `tb_Pessoa_Juridica_id_Pessoa_Juridica` INT NULL,
  PRIMARY KEY (`id_contato`),
  INDEX `fk_tb_Contato_tb_Seguradora1_idx` (`tb_Seguradora_id_seguradora` ASC),
  INDEX `fk_tb_Contato_tb_Pessoa_Juridica1_idx` (`tb_Pessoa_Juridica_id_Pessoa_Juridica` ASC),
  CONSTRAINT `fk_tb_Contato_tb_Seguradora1`
    FOREIGN KEY (`tb_Seguradora_id_seguradora`)
    REFERENCES `SolaFide_v6`.`tb_Seguradora` (`id_seguradora`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_Contato_tb_Pessoa_Juridica1`
    FOREIGN KEY (`tb_Pessoa_Juridica_id_Pessoa_Juridica`)
    REFERENCES `SolaFide_v6`.`tb_Pessoa_Juridica` (`id_Pessoa_Juridica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Recibo` (
  `id_recibo` INT NOT NULL AUTO_INCREMENT,
  `pg` VARCHAR(2) NULL,
  `apolice` VARCHAR(75) NULL,
  `nome_cliente` VARCHAR(75) NULL,
  `Seguradora` VARCHAR(75) NULL,
  `parcelas` INT NULL,
  `Premio` DOUBLE NULL,
  `perc_comissao` INT(3) NULL,
  `comissao_bruta` VARCHAR(15) NULL,
  `desconto` VARCHAR(15) NULL,
  `liquido` VARCHAR(15) NULL,
  `valor_pago` VARCHAR(15) NULL,
  `valor_pagar` VARCHAR(15) NULL,
  `dt_pagamento` VARCHAR(14) NULL,
  PRIMARY KEY (`id_recibo`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Principal_Condutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Principal_Condutor` (
  `id_principal_condutor` INT NOT NULL AUTO_INCREMENT,
  `especifique` VARCHAR(20) NULL,
  `tb_Pessoa_Fisica_id_Pessoa_Fisica` INT NULL,
  `tb_Pessoa_Juridica_id_Pessoa_Juridica` INT NULL,
  `tb_Questionario_Seguro_Auto_id_questionario` INT NULL,
  `Reside_Em` VARCHAR(40) NULL,
  `Nome_princ_condut` VARCHAR(75) NULL,
  PRIMARY KEY (`id_principal_condutor`),
  INDEX `fk_tb_Principal_Condutor_tb_Pessoa_Fisica1_idx` (`tb_Pessoa_Fisica_id_Pessoa_Fisica` ASC),
  INDEX `fk_tb_Principal_Condutor_tb_Pessoa_Juridica1_idx` (`tb_Pessoa_Juridica_id_Pessoa_Juridica` ASC),
  INDEX `fk_tb_Principal_Condutor_tb_Questionario_Seguro_Auto1_idx` (`tb_Questionario_Seguro_Auto_id_questionario` ASC),
  CONSTRAINT `fk_tb_Principal_Condutor_tb_Pessoa_Fisica1`
    FOREIGN KEY (`tb_Pessoa_Fisica_id_Pessoa_Fisica`)
    REFERENCES `SolaFide_v6`.`tb_Pessoa_Fisica` (`id_Pessoa_Fisica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_Principal_Condutor_tb_Pessoa_Juridica1`
    FOREIGN KEY (`tb_Pessoa_Juridica_id_Pessoa_Juridica`)
    REFERENCES `SolaFide_v6`.`tb_Pessoa_Juridica` (`id_Pessoa_Juridica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_Principal_Condutor_tb_Questionario_Seguro_Auto1`
    FOREIGN KEY (`tb_Questionario_Seguro_Auto_id_questionario`)
    REFERENCES `SolaFide_v6`.`tb_Questionario_Seguro_Auto` (`id_questionario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Estacionamento_Escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Estacionamento_Escola` (
  `id_estacionamento_escola` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(10) NULL,
  `tb_Questionario_id_questionario` INT NOT NULL,
  PRIMARY KEY (`id_estacionamento_escola`),
  INDEX `fk_tb_Estacionamento_Escola_tb_Questionario1_idx` (`tb_Questionario_id_questionario` ASC),
  CONSTRAINT `fk_tb_Estacionamento_Escola_tb_Questionario1`
    FOREIGN KEY (`tb_Questionario_id_questionario`)
    REFERENCES `SolaFide_v6`.`tb_Questionario_Seguro_Auto` (`id_questionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Periodo_Estudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Periodo_Estudo` (
  `id_periodo_estudo` INT NOT NULL AUTO_INCREMENT,
  `matutino` VARCHAR(3) NULL,
  `vespertino` VARCHAR(3) NULL,
  `noturno` VARCHAR(3) NULL,
  `tb_Questionario_id_questionario` INT NULL,
  PRIMARY KEY (`id_periodo_estudo`),
  INDEX `fk_tb_Periodo_Estudo_tb_Questionario1_idx` (`tb_Questionario_id_questionario` ASC),
  CONSTRAINT `fk_tb_Periodo_Estudo_tb_Questionario1`
    FOREIGN KEY (`tb_Questionario_id_questionario`)
    REFERENCES `SolaFide_v6`.`tb_Questionario_Seguro_Auto` (`id_questionario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Filho_Enteado_17_Anos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Filho_Enteado_17_Anos` (
  `id_filho_enteado_17_anos` INT NOT NULL AUTO_INCREMENT,
  `qnt_filhos` INT(3) NULL,
  `idade` VARCHAR(3) NULL,
  `tb_Questionario_id_questionario` INT NULL,
  PRIMARY KEY (`id_filho_enteado_17_anos`),
  INDEX `fk_tb_Filho_Enteado_17_Anos_tb_Questionario1_idx` (`tb_Questionario_id_questionario` ASC),
  CONSTRAINT `fk_tb_Filho_Enteado_17_Anos_tb_Questionario1`
    FOREIGN KEY (`tb_Questionario_id_questionario`)
    REFERENCES `SolaFide_v6`.`tb_Questionario_Seguro_Auto` (`id_questionario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Comissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Comissoes` (
  `id_Comissoes` INT NOT NULL AUTO_INCREMENT,
  `pago` VARCHAR(4) NULL,
  `apolice` VARCHAR(30) NULL,
  `valor_pago` VARCHAR(15) NULL,
  `valor_pagar` VARCHAR(15) NULL,
  `dt_pagamento` VARCHAR(14) NULL,
  `nome_cliente` VARCHAR(45) NULL,
  `seguradora` VARCHAR(75) NULL,
  `parcelas` INT NULL,
  `Premio` DOUBLE NULL,
  `perc_comissao` INT(3) NULL,
  `comissao_bruta` VARCHAR(15) NULL,
  `desconto` VARCHAR(15) NULL,
  `liquido` VARCHAR(15) NULL,
  PRIMARY KEY (`id_Comissoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Estacionamento_Residencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Estacionamento_Residencia` (
  `id_Estacionamento_Residencia` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(10) NULL,
  `tb_Questionario_id_questionario` INT NOT NULL,
  PRIMARY KEY (`id_Estacionamento_Residencia`),
  INDEX `fk_tb_Estacionamento_Residencia_tb_Questionario1_idx` (`tb_Questionario_id_questionario` ASC),
  CONSTRAINT `fk_tb_Estacionamento_Residencia_tb_Questionario1`
    FOREIGN KEY (`tb_Questionario_id_questionario`)
    REFERENCES `SolaFide_v6`.`tb_Questionario_Seguro_Auto` (`id_questionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Garagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Garagem` (
  `id_Estacionamento_Trabalho` INT NOT NULL AUTO_INCREMENT,
  `residencia` VARCHAR(40) NULL,
  `trabalho` VARCHAR(3) NULL,
  `local_estudos` VARCHAR(3) NULL,
  `tb_Questionario_id_questionario` INT NULL,
  PRIMARY KEY (`id_Estacionamento_Trabalho`),
  INDEX `fk_tb_Estacionamento_Trabalho_tb_Questionario1_idx` (`tb_Questionario_id_questionario` ASC),
  CONSTRAINT `fk_tb_Estacionamento_Trabalho_tb_Questionario1`
    FOREIGN KEY (`tb_Questionario_id_questionario`)
    REFERENCES `SolaFide_v6`.`tb_Questionario_Seguro_Auto` (`id_questionario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Contato_Pessoal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Contato_Pessoal` (
  `id_Contato_Pessoal` INT NOT NULL AUTO_INCREMENT,
  `tel_residencial` VARCHAR(10) NOT NULL,
  `tel_recado` VARCHAR(10) NULL,
  `cel_pessoal` VARCHAR(11) NULL,
  `nextel` VARCHAR(15) NULL,
  `email` VARCHAR(50) NULL,
  `tb_Pessoa_Fisica_id_Pessoa_Fisica` INT NULL,
  PRIMARY KEY (`id_Contato_Pessoal`),
  INDEX `fk_tb_Contato_Pessoal_tb_Pessoa_Fisica1_idx` (`tb_Pessoa_Fisica_id_Pessoa_Fisica` ASC),
  CONSTRAINT `fk_tb_Contato_Pessoal_tb_Pessoa_Fisica1`
    FOREIGN KEY (`tb_Pessoa_Fisica_id_Pessoa_Fisica`)
    REFERENCES `SolaFide_v6`.`tb_Pessoa_Fisica` (`id_Pessoa_Fisica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_Item` (
  `id_Item` INT NOT NULL AUTO_INCREMENT,
  `item` VARCHAR(20) NULL,
  `tb_Pessoa_Juridica_id_Pessoa_Juridica` INT NULL,
  `tb_Pessoa_Fisica_id_Pessoa_Fisica` INT NULL,
  PRIMARY KEY (`id_Item`),
  INDEX `fk_table1_tb_Pessoa_Juridica1_idx` (`tb_Pessoa_Juridica_id_Pessoa_Juridica` ASC),
  INDEX `fk_Item_tb_Pessoa_Fisica1_idx` (`tb_Pessoa_Fisica_id_Pessoa_Fisica` ASC),
  CONSTRAINT `fk_table1_tb_Pessoa_Juridica1`
    FOREIGN KEY (`tb_Pessoa_Juridica_id_Pessoa_Juridica`)
    REFERENCES `SolaFide_v6`.`tb_Pessoa_Juridica` (`id_Pessoa_Juridica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Item_tb_Pessoa_Fisica1`
    FOREIGN KEY (`tb_Pessoa_Fisica_id_Pessoa_Fisica`)
    REFERENCES `SolaFide_v6`.`tb_Pessoa_Fisica` (`id_Pessoa_Fisica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_lista_Marca_Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_lista_Marca_Veiculo` (
  `id_lista_veiculo` INT NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(45) NULL,
  PRIMARY KEY (`id_lista_veiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_lista_Nome_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_lista_Nome_veiculo` (
  `id_lista_Nome_veiculo` INT NOT NULL AUTO_INCREMENT,
  `Nome_veiculo` VARCHAR(45) NULL,
  `tb_lista_Marca_Veiculo_id_lista_veiculo` INT NULL,
  PRIMARY KEY (`id_lista_Nome_veiculo`),
  INDEX `fk_tb_lista_Nome_veiculo_tb_lista_Marca_Veiculo1_idx` (`tb_lista_Marca_Veiculo_id_lista_veiculo` ASC),
  CONSTRAINT `fk_tb_lista_Nome_veiculo_tb_lista_Marca_Veiculo1`
    FOREIGN KEY (`tb_lista_Marca_Veiculo_id_lista_veiculo`)
    REFERENCES `SolaFide_v6`.`tb_lista_Marca_Veiculo` (`id_lista_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_client_sinistro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_client_sinistro` (
  `id_client_sinistro` INT NOT NULL AUTO_INCREMENT,
  `tb_Sinistro_id_sinistro` INT NULL,
  `cod_cliente` INT NULL,
  `nome_cliente` VARCHAR(45) NULL,
  `tb_Dados_Veiculo_id_Dados_Veiculo` INT NULL,
  `modelo` VARCHAR(45) NULL,
  `fabricante` VARCHAR(45) NULL,
  PRIMARY KEY (`id_client_sinistro`),
  INDEX `fk_tb_client_sinistro_tb_Sinistro1_idx` (`tb_Sinistro_id_sinistro` ASC),
  INDEX `fk_tb_client_sinistro_tb_Dados_Veiculo1_idx` (`tb_Dados_Veiculo_id_Dados_Veiculo` ASC),
  CONSTRAINT `fk_tb_client_sinistro_tb_Sinistro1`
    FOREIGN KEY (`tb_Sinistro_id_sinistro`)
    REFERENCES `SolaFide_v6`.`tb_Sinistro` (`id_sinistro`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_client_sinistro_tb_Dados_Veiculo1`
    FOREIGN KEY (`tb_Dados_Veiculo_id_Dados_Veiculo`)
    REFERENCES `SolaFide_v6`.`tb_Dados_Veiculo` (`id_Dados_Veiculo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_client_MontApolice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_client_MontApolice` (
  `id_client_MontApolice` INT NOT NULL AUTO_INCREMENT,
  `tb_MontagemApolice_id_MontagemApolice` INT NULL,
  `cod_cliente` INT NULL,
  `nome_cliente` VARCHAR(75) NULL,
  `tb_Dados_Veiculo_id_Dados_Veiculo` INT NULL,
  `modelo` VARCHAR(30) NULL,
  `fabricante` VARCHAR(30) NULL,
  PRIMARY KEY (`id_client_MontApolice`),
  INDEX `fk_tb_client_orcamento_tb_Dados_Veiculo1_idx` (`tb_Dados_Veiculo_id_Dados_Veiculo` ASC),
  INDEX `fk_tb_client_orcamento_tb_MontagemApolice1_idx` (`tb_MontagemApolice_id_MontagemApolice` ASC),
  CONSTRAINT `fk_tb_client_orcamento_tb_Dados_Veiculo1`
    FOREIGN KEY (`tb_Dados_Veiculo_id_Dados_Veiculo`)
    REFERENCES `SolaFide_v6`.`tb_Dados_Veiculo` (`id_Dados_Veiculo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_client_orcamento_tb_MontagemApolice1`
    FOREIGN KEY (`tb_MontagemApolice_id_MontagemApolice`)
    REFERENCES `SolaFide_v6`.`tb_MontagemApolice` (`id_MontagemApolice`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SolaFide_v6`.`tb_cliente_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolaFide_v6`.`tb_cliente_veiculo` (
  `id_cliente_veiculo` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente_veiculo` VARCHAR(45) NULL,
  `tb_Questionario_Seguro_Auto_id_questionario` INT NULL,
  PRIMARY KEY (`id_cliente_veiculo`),
  INDEX `fk_tb_cliente_veiculo_tb_Questionario_Seguro_Auto1_idx` (`tb_Questionario_Seguro_Auto_id_questionario` ASC),
  CONSTRAINT `fk_tb_cliente_veiculo_tb_Questionario_Seguro_Auto1`
    FOREIGN KEY (`tb_Questionario_Seguro_Auto_id_questionario`)
    REFERENCES `SolaFide_v6`.`tb_Questionario_Seguro_Auto` (`id_questionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
